# Generated by Django 5.2 on 2025-04-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
    ]
